/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  PasswordChanges: () => import('#controllers/password_changes_controller'),
  PasswordResets: () => import('#controllers/password_resets_controller'),
  Session: () => import('#controllers/session_controller'),
  Teams: () => import('#controllers/teams_controller'),
}
